server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: taxicall
          uri: http://localhost:8081
          predicates:
            - Path=/taxiCalls/** 
        - id: taximanage
          uri: http://localhost:8082
          predicates:
            - Path=/taxiManagements/** 
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path= /Taxicallinfo/**
        - id: taxiassign
          uri: http://localhost:8084
          predicates:
            - Path=/taxiAssigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: taxicall
          uri: http://taxicall:8080
          predicates:
            - Path=/taxiCalls/** 
        - id: taximanage
          uri: http://taximanage:8080
          predicates:
            - Path=/taxiManagements/** 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path= /Taxicallinfo/**
        - id: taxiassign
          uri: http://taxiassign:8080
          predicates:
            - Path=/taxiAssigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
